I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/debug/tile_editor_logic.rpy", line 19, in script
    python:
  File "game/debug/tile_editor_logic.rpy", line 21, in <module>
    debug_.draw_on_tile( debug_.tilebrush )
  File "game/debug/debug_functions.rpy", line 280, in draw_on_tile
    game.grid[where[1]][where[0]] = Square(x=where[0], y=where[1], type = what )
TypeError: __init__() takes exactly 5 arguments (4 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/debug/tile_editor_logic.rpy", line 19, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/debug/tile_editor_logic.rpy", line 21, in <module>
    debug_.draw_on_tile( debug_.tilebrush )
  File "game/debug/debug_functions.rpy", line 280, in draw_on_tile
    game.grid[where[1]][where[0]] = Square(x=where[0], y=where[1], type = what )
TypeError: __init__() takes exactly 5 arguments (4 given)

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
ParisIsBurning 1.0
Sat Feb 26 20:24:57 2022
